-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, B.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE AS A LEFT JOIN USER_INFO AS B ON A.USER_ID = B.USER_ID
# WHERE B.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
HAVING B.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER