-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A LEFT JOIN CAR_RENTAL_COMPANY_CAR AS B
ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE LIKE '세단' AND MONTH(A.START_DATE) LIKE '10'
ORDER BY A.CAR_ID DESC
