-- 코드를 작성해주세요
SELECT SUM(A.SCORE) AS 'SCORE', A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_GRADE AS A LEFT JOIN HR_EMPLOYEES AS B
ON A.EMP_NO = B.EMP_NO
WHERE A.YEAR = 2022
GROUP BY A.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
