-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", A.BOARD_ID, "/", A.FILE_ID, A.FILE_NAME, A.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS A LEFT JOIN USED_GOODS_BOARD AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY A.FILE_ID DESC